import { FontProperties, KAGEData, Path } from "./types";
import { PathOp } from "./curve/path";

/**
 * Abstract font base class. The main responsibility of the Font class is to
 * take KAGE stroke data and generate path/SVG data.
 */
export abstract class Font {
  /**
   * Takes in an object containing properties to set for the font such as width,
   * connection type, end type, and so on.
   *
   * This is intentionally separated from the constructor so that font
   * properties may be changed without creating a new Font object.
   */
  abstract setProperties(properties: FontProperties): void;

  /**
   * Takes in an array of KAGE stroke data and returns an array of Path objects.
   */
  abstract getPaths(strokes: KAGEData[]): Path[];

  /**
   * Returns the font's overrides hash.
   */
  abstract getOverrides(): object;

  /**
   * Takes in a path that is assumed to be generated by this font's getPath()
   * and returns a generated SVG.
   */
  generateSVG(paths: Path[]): string {
    let buffer = "";
    buffer += "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" baseProfile=\"full\" viewBox=\"0 0 200 200\" width=\"200\" height=\"200\">\n";

    for(let path of paths) {
      buffer += "<path d=\"";
      buffer += PathOp.toSVGSequence(path, 5);
      buffer += "\" fill=\"black\" />\n";
    }

    buffer += "</svg>\n";

    return buffer;
  }

  /**
   * Takes in a path that is assumed to be generated by this font's getPath()
   * and returns a font glyph. Currently unused and font format unknown.
   */
  //generateFont(path): string;
}
